# Generated by Django 5.2.12 on 2026-03-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('TL', 'Team Lead'), ('EMP', 'Employee'), ('PC', 'Project Coordinator')], default='EMP', max_length=3),
        ),
    ]
